language: node_js
node_js:
  - "0.11"
  - "0.12"
before_install:
  - npm install --global gulp
  - npm install -g codeclimate-test-reporter
install:
  - npm install
after_script:
  - npm test && codeclimate < coverage/reports/lcov.info