language: node_js
node_js:
  - "0.12"
before_install:
  - npm install --global gulp
  - npm install -g codeclimate-test-reporter
install:
  - npm install
after_script:
  - codeclimate < coverage/lcov.info
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && make deploy